-- ParkEase database setup for Supabase
-- Run this entire file in Supabase Dashboard -> SQL Editor.
-- This schema uses Supabase Auth for passwords/sessions and Postgres RLS
-- for user-owned data.

create extension if not exists pgcrypto;

-- 1) User profile
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  university_id text,
  department text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- 2) Automatically create a profile after Supabase Auth signup.
create schema if not exists private;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, university_id, department)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'ParkEase User'),
    new.raw_user_meta_data->>'university_id',
    new.raw_user_meta_data->>'department'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure private.handle_new_user();

-- 3) Historical route/parking patterns used by the prototype.
create table if not exists public.route_patterns (
  id bigint generated by default as identity primary key,
  route text not null,
  time_slot text not null,
  congestion_level text not null check (congestion_level in ('Low','Medium','High')),
  parking_difficulty text not null check (parking_difficulty in ('Low','Medium','High')),
  informal_parking_zone text not null,
  avg_extra_minutes integer not null default 0,
  carpool_pool_size integer not null default 0,
  unique(route, time_slot)
);

alter table public.route_patterns enable row level security;

drop policy if exists "Route patterns are readable" on public.route_patterns;
create policy "Route patterns are readable"
on public.route_patterns for select
to anon, authenticated
using (true);

-- Seed route data. Safe to run repeatedly.
insert into public.route_patterns
(route,time_slot,congestion_level,parking_difficulty,informal_parking_zone,avg_extra_minutes,carpool_pool_size)
values
('Uvarsad Road','08:30-09:30','High','High','Karnavati University North Lot',12,3),
('Uvarsad Road','09:30-11:00','Low','Medium','Karnavati University North Lot',3,1),
('Adalaj Bypass','08:30-09:30','Medium','Low','Roadside near Adalaj Circle',6,2),
('Adalaj Bypass','09:30-11:00','Low','Low','Roadside near Adalaj Circle',2,0),
('GH-0 Road (Gandhinagar-Ahmedabad Highway)','08:00-09:00','High','High','Society compound near Kudasan',15,4),
('GH-0 Road (Gandhinagar-Ahmedabad Highway)','17:30-19:00','High','High','Society compound near Kudasan',14,4),
('Kudasan Market Road','10:00-12:00','Medium','High','Market roadside parking',8,1),
('Kudasan Market Road','15:00-17:00','Low','Medium','Market roadside parking',4,1),
('Sector 21-22 Road','08:30-09:30','Medium','Medium','Sector 21 campus ground',7,2),
('Sector 21-22 Road','13:00-14:00','Low','Low','Sector 21 campus ground',2,0),
('Infocity Road','09:00-10:00','High','High','Infocity roadside',10,3),
('Infocity Road','18:00-19:30','High','High','Infocity roadside',13,3)
on conflict (route,time_slot) do update set
  congestion_level=excluded.congestion_level,
  parking_difficulty=excluded.parking_difficulty,
  informal_parking_zone=excluded.informal_parking_zone,
  avg_extra_minutes=excluded.avg_extra_minutes,
  carpool_pool_size=excluded.carpool_pool_size;

-- 4) Personal trip history.
create table if not exists public.trip_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  origin text not null,
  destination text not null,
  arrival_time text not null,
  congestion_level text,
  extra_minutes integer,
  parking_zone text,
  time_saved_minutes numeric(6,2) default 0,
  fuel_saved_l numeric(6,3) default 0,
  co2_saved_kg numeric(7,3) default 0,
  created_at timestamptz not null default now()
);

alter table public.trip_history enable row level security;

drop policy if exists "Users can view own trips" on public.trip_history;
create policy "Users can view own trips"
on public.trip_history for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own trips" on public.trip_history;
create policy "Users can insert own trips"
on public.trip_history for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own trips" on public.trip_history;
create policy "Users can delete own trips"
on public.trip_history for delete
to authenticated
using ((select auth.uid()) = user_id);

-- 5) Anonymous community parking reports linked to the signed-in account.
create table if not exists public.parking_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  route text not null,
  destination text,
  status text not null check (status in ('available','full')),
  created_at timestamptz not null default now()
);

alter table public.parking_reports enable row level security;

drop policy if exists "Authenticated users can view reports" on public.parking_reports;
create policy "Authenticated users can view reports"
on public.parking_reports for select
to authenticated
using (true);

drop policy if exists "Users can submit reports" on public.parking_reports;
create policy "Users can submit reports"
on public.parking_reports for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- 6) Saved parking spots.
create table if not exists public.saved_spots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  spot_name text not null,
  route text,
  created_at timestamptz not null default now()
);

alter table public.saved_spots enable row level security;

drop policy if exists "Users can view own saved spots" on public.saved_spots;
create policy "Users can view own saved spots"
on public.saved_spots for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can save spots" on public.saved_spots;
create policy "Users can save spots"
on public.saved_spots for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own saved spots" on public.saved_spots;
create policy "Users can delete own saved spots"
on public.saved_spots for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Helpful indexes
create index if not exists trip_history_user_id_created_at_idx
on public.trip_history(user_id, created_at desc);

create index if not exists parking_reports_route_created_at_idx
on public.parking_reports(route, created_at desc);

create index if not exists saved_spots_user_id_idx
on public.saved_spots(user_id);

-- 7) Explicit least-privilege grants for the browser Data API.
revoke all on table public.profiles, public.route_patterns, public.trip_history,
  public.parking_reports, public.saved_spots from anon, authenticated;

grant select on public.route_patterns to anon, authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.trip_history to authenticated;
grant select, insert on public.parking_reports to authenticated;
grant select, insert, delete on public.saved_spots to authenticated;

-- Identity columns used by inserts.
grant usage, select on all sequences in schema public to authenticated;
